### PR TITLE
Version 0.12.5

### PR DESCRIPTION
**Pull request by map7**
Here is the new version I found in another fork, maybe this should be merged into the main gem?

### CODE REVIEW

**Comment by bary822** [comment]
@unixmonkey 
Any chances merging this, if the conflict is resolved?

**Comment by saurabh-prohaktiv** [comment]
@map7, @unixmonkey just FYI, this fork contains the binaries for `0.12.5-rc` and not `0.12.5` (I don't think that there is any difference between the two but I am not sure), also after `0.12.5` got released, I saw that it has various builds for various OS as you can see [here](https://wkhtmltopdf.org/downloads.html) and are not just generic builds for linux and mac as they were before.

**Comment by map7** [comment]
No there hasn't been, I'm using the wkhtmltopdf binary in my ansible 
scripts instead of this now.

**Comment by t-richard** [comment]
Hello, is there any news on this PR ? Is a new PR going to be created as said in #46 ?

**Comment by AlexandrePavy** [comment]
Hello, any news on this ?

**Comment by pedrofurtado** [comment]
@zakird @unixmonkey Any news? 👍

**Comment by pedrofurtado** [comment]
@unixmonkey I think this PR should be closed :+1: the binary version is already updated :+1:

**Pull request closed without merging**
