### PR TITLE
Add binary for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by anatoliliotych**

### CODE REVIEW

**Comment by elissonmichael** [comment]
Thanks for updating this.

**Comment by MarcusPetri** [comment]
Any predictions to merge into the master? (rubygems too)

**Comment by maxfurman** [comment]
Any updates on merging this? We've upgraded our server to 22.04 already but this gem hasn't been updated in two years. What is a reasonable timeline to expect new Ubuntu versions in a gem meant to manage a certain binary across OS versions?

**Comment by anatoliliotych** [comment]
>

**Comment by roostinghawk** [comment]
Could you please merge and upload to gem? Thanks a lot!

**Comment by roostinghawk** [comment]
> So I've tried to use this in heroku-22 stack and got some issues, so I had to switch to use the same version of binary as ubuntu 20 uses which also didn't help. After that I've switched to https://github.com/rposborne/wkhtmltopdf-heroku

Is there any difference?

**Comment by anatoliliotych** [comment]
> 

I didn't dig into Heroku version gem, but it helped.

**Comment by roostinghawk** [comment]
Thanks. Since our project was using wkhtmltopdf_binary_gem, I would like to keep it. Is there anyway to use before maintainer's approval?

**Comment by anatoliliotych** [comment]
> Thanks. Since our project was using wkhtmltopdf_binary_gem, I would like to keep it. Is there anyway to use before maintainer's approval?

I'd say no. you can fork and switch back as soon as it will be merged.

**Comment by roostinghawk** [comment]
> I'd say no. you can fork and switch back as soon as it will be merged.
Plan to fork and generate ubuntu22 binary file by myself. Could you tell me how to generate this file? Thanks

**Comment by anatoliliotych** [comment]
> 

I just used official ubuntu repo with installed package. It was long ago :)

**Comment by unixmonkey** [comment]
@anatoliliotych Would you mind terribly replacing the binary with the most recent one? I'd be happy to merge and release with that.

**Comment by anatoliliotych** [comment]
> 

I'm going to do this a little bit later today. :)

**Comment by anatoliliotych** [comment]
So just to leave some instructions for the future:
1. Download proper version of package https://wkhtmltopdf.org/downloads.html
2. Unpack package and get binary from archive `usr/loca/bin/wkhtmltopdf`
3. Rename binary to match OS version. `mv wkhtmltopdf wkhtmltopdf_ubuntu_22.04_amd64`
4. Pack binary, for example `tar -cvzf wkhtmltopdf_ubuntu_22.04_amd64.gz wkhtmltopdf_ubuntu_22.04_amd64`
5. Profit :)

**Comment by anatoliliotych** [comment]
@unixmonkey please, review my previous comment and PR.

**Comment by anatoliliotych** [comment]
@unixmonkey could you trigger workflow?

**Comment by unixmonkey** [comment]
@anatoliliotych Thanks! Have you verified that this works on your Ubuntu 22 system yet?

**Comment by anatoliliotych** [comment]
> @anatoliliotych Thanks! Have you verified that this works on your Ubuntu 22 system yet?

@unixmonkey test is failing with `Syntax error: Unterminated quoted string` and this is what I've met with previous binaries.

**Comment by anatoliliotych** [comment]
> @anatoliliotych I tried this on heroku with stack `heroku-22` and it failed out. I tried extracting the binary and myself and noticed that the md5 hash of yours and mine are different(I didn't look into the actual binary). The steps I took to reproduce were similar to yours, but I used the `gzip` command to pack the binary as it suggests in the README.
> 
> So doing:
> 
> 1. Download proper version of package https://wkhtmltopdf.org/downloads.html
> 2. Unpack package and get binary from archive usr/loca/bin/wkhtmltopdf
> 3. Rename binary to match OS version. `mv wkhtmltopdf wkhtmltopdf_ubuntu_22.04_amd64`
> 4. Pack binary, for example `gzip --best wkhtmltopdf_ubuntu_22.04_amd64`
> 
> Doing that final command like that gave me something that now works on Heroku

Super strange how packing can break it :) Let me replace it.

**Comment by night91** [comment]
Any plans to go ahead with this PR?

**Comment by unixmonkey** [comment]
I used a different PR, but support for Ubuntu 22.04 is now released in version 0.12.6.6 of this gem. Thank you all for your help, and please let me know if you have any issues!

**Pull request closed without merging**
