### PR TITLE
Support for CentOS 8

### LINKED ISSUE #66: Is it possible to release a version with CentOS 8 binary?
Recently was released the binary version for CentOS 8: 

https://wkhtmltopdf.org/downloads.html
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox-0.12.5-1.centos8.x86_64.rpm
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4519
https://github.com/wkhtmltopdf/packaging/issues/40
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4490

@unixmonkey @zakird Is it possible to release a version with CentOS 8 binary?

### PR DESCRIPTION
**Pull request by pedrofurtado**
Closes #66

@unixmonkey @zakird 👍

### CODE REVIEW

**Comment by pedrofurtado** [comment]
Our internal application is using the fork related to this PR, and it is working well 🎉 
Happy to see it merged and released asap 🥇

**Comment by DiegoZurita** [comment]
I tried it and work out. A great improve!

**Comment by WillRadi** [comment]
Thanks @pedrofurtado! Worked soooo well!

**Comment by pedrofurtado** [comment]
@unixmonkey Thanks. Happy to see a new release with CentOS 8 🎉 🍻

**Comment by unixmonkey** [comment]
This is now released as part of version 0.12.5.2

Thank you very much for your help! 🥇

**Pull request merged**
