### PR TITLE
Add support for amd64/arm64/i386 on debian 11

### PR DESCRIPTION
**Pull request by lusinh**
I upgrade code from https://github.com/zakird/wkhtmltopdf_binary_gem/pull/143.
- Update test for new version of wkhtmltopdf
- Add more library for arm64 and i386

### CODE REVIEW

**Comment by legendetm** [comment]
@stuyam can you approve the CI workflow for this PR as this adds better support for Debian 11?

**Comment by stuyam** [comment]
@legendetm wish I could but I am not a maintainer 😉 but maybe @unixmonkey can help!

**Comment by daniellytle** [comment]
@unixmonkey could you take a look?

**Comment by daniellytle** [comment]
@unixmonkey ?

**Comment by daniellytle** [comment]
@unixmonkey any update?

**Comment by JrmKrb** [comment]
@unixmonkey Could we get it deployed?

**Comment by unixmonkey** [comment]
Thank you! Although I didn't merge this specific PR, these Debian binaries are now in version `0.12.6.7` (from [this PR](https://github.com/zakird/wkhtmltopdf_binary_gem/pull/145)). Please check it and make sure it works for you.

**Pull request closed without merging**
