### PR TITLE
Add support for Linux Mint 19.2 

### PR DESCRIPTION
**Pull request by alextakitani**
Created a link for Linux Mint 19.2  pointing to Ubuntu 18.04 binaries.

The same would work for other Ubuntu derivatives.

### CODE REVIEW

**Comment by hlascelles** [comment]
Ditto for 19/19.1. Shall I commit to this branch?

`wkhtmltopdf_linuxmint_19_amd64.gz => same`

**Comment by hlascelles** [comment]
And maybe more generally, a config for this gem to allow a pointer to a known compatible version (with a friendly request to open a PR like this)? Work for another PR certainly.

**Comment by unixmonkey** [comment]
Thank you for this, but I'd much prefer changing [the binstub](https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/bin/wkhtmltopdf) to reference the correct source binary instead of a symlink if that's possible. Will that work for you?

**Comment by unixmonkey** [comment]
I've gone ahead and rolled this into the binstub [as you can see here](https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/bin/wkhtmltopdf#L17), so I'm going to close this PR, since it shouldn't be necessary any longer.

Please test this and make sure it works for you, if not, please reopen this and we will get it figured out.

Thank you for your help. 😃

**Comment by unixmonkey** [comment]
Forgot to mention, the new release that includes this is version 0.12.5.2.

**Pull request closed without merging**
