### PR TITLE
Upgrade to 0.12.6 version of wkhtmltopdf

### LINKED ISSUE #80: How to upgrade to wkhtmltopdf 0.12.6?
@unixmonkey  @zakird Hey guys!

A new release of wkhtmltopdf is out (0.12.6 -> https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.6 ).

How to upgrade the gem to get this release? I can open a PR to contribute with it. I just need help about what steps I should follow hehe 👍 🤝

### PR DESCRIPTION
**Pull request by pedrofurtado**
Closes #80  @unixmonkey  @zakird 👍 

Related issues:
https://github.com/wkhtmltopdf/packaging/issues/70

### CODE REVIEW

**Comment by pedrofurtado** [comment]
cc @willradi

**Comment by pedrofurtado** [comment]
@zakird @unixmonkey 

About deepin OS and macOS Cocoa, I really have no idea about how to build them for this PR 😄 
Is really worth to support it?

**Comment by unixmonkey** [comment]
1. Did you build these binaries or download them from https://wkhtmltopdf.org/downloads.html or https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-1

I'd prefer to use the official releases and will be verifying MD5s match if possible.

2. As far as I know, Carbon is for OS8 and OS9 (but runs on OSX up to Catalina), so I think we only need the Cocoa binaries, which can probably be extracted from the installer.

3. I don't know much about Deepin, but currently it doesn't use it's own binary, but instead detects and loads the Debian package [as shown here](https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/bin/wkhtmltopdf#L28).

**Comment by pedrofurtado** [comment]
@unixmonkey Thanks for feedback! 😄 

I have downloaded all releases from https://wkhtmltopdf.org/downloads.html, one a one, and executing the steps for build described in README.md ( https://github.com/pedrofurtado/wkhtmltopdf_binary_gem#extracting-binaries )

**Comment by pedrofurtado** [comment]
@unixmonkey  Right now, I am testing in our application, that uses Centos 7 and CentOS 8, to verify if everything is ok 👍

**Comment by pedrofurtado** [comment]
@unixmonkey  Could you help me to build the 0.12.6 for MacOS cocoa? I dont have a mac computer hehehe

**Comment by unixmonkey** [comment]
I can do that if you grant me push access to your fork, or you can use the "extracting binaries" instructions. I just tested that out, and after running those commands you get a `.tar.gz` file, that once unpacked, all you need is the wkhtmltopdf binary (48M), which gzips down to 16M.

**Comment by pedrofurtado** [comment]
Great! I grant access for you in my fork @unixmonkey 👍

**Comment by pedrofurtado** [comment]
For each binary, I execute the build steps and then I gzip and renamed the gzipped file, to upload in fork. For a while, our application is working well. I am testing in dev environment, in a few days I will test in staging 👍

**Comment by pedrofurtado** [comment]
The 0.12.6 version has a breaking change option, that is true by default, related to local file access. I opened a PR for this in the wicked_pdf 👍 

Link for PR: https://github.com/mileszs/wicked_pdf/pull/920

**Comment by pedrofurtado** [comment]
@unixmonkey Great news!

I modified temporarily the Gemfile of our application, to something like this:

```ruby
gem 'wicked_pdf', git: 'https://github.com/pedrofurtado/wicked_pdf', branch: 'master'
gem 'wkhtmltopdf-binary', git: 'https://github.com/pedrofurtado/wkhtmltopdf_binary_gem', branch: 'patch-1'
```

With this 2 PRs, one in binary gem and another in wicked_pdf gem, everything worked perfectly. The second PR in wicked_pdf add a flag indicating if dev want or not enable local file access 🤝

**Comment by pedrofurtado** [comment]
The only thing still pending, for a while, is the file ".gz" for macOS cocoa in 0.12.6 ✅

**Comment by pedrofurtado** [comment]
@unixmonkey Is there something pending yet? in PR 🎉

**Comment by pedrofurtado** [comment]
All Ubuntu, Debian and CentOS worked perfectly 👍  I've tested here with some of Vagrant + Virtualbox 🥂 

I cannot test only the macOS-based binary, but if you builded and worked well, so is ok 👍 🏆

**Comment by unixmonkey** [comment]
Only that I haven't gotten around to testing it and putting out a build. I should be able to get to that today or tomorrow.

**Comment by pedrofurtado** [comment]
No problem! 🤝  Thanks you so much for your time and patience to test a big PR like this one 👍 😆

**Comment by pedrofurtado** [comment]
Anyway, I will be pleasure to help you in anything you need 👍  Thanks again for your hard work in maintaince of wicked_pdf gem and this gem 🍻

**Comment by unixmonkey** [comment]
This seems to be working well, so I've merged and published this to version 0.12.6.

Thank you so much for your help!

**Pull request merged**
