### PR TITLE
Update version to 0.12.4

### PR DESCRIPTION
**Pull request by ownadi**

### CODE REVIEW

**Comment by dwkoogt** [comment]
+1
Encountered same problem as below.
https://stackoverflow.com/questions/41582504/wicked-pdf-not-rendering-header-footer

**Comment by avenavo** [comment]
+1

**Comment by baloran** [comment]
Some news about merge ?

**Comment by unixmonkey** [comment]
@baloran Have you tested this to make it works for you?

**Comment by gkop** [comment]
This passed a basic smoke test for me.

Also checked the fingerprints against https://wkhtmltopdf.org/downloads.html , they check out!

7ff1b7735599201b6a17725497aa732ba1278ec5  wkhtmltopdf_linux_x86
2c075a8f64b0a2efd95cc8ec25f02fa560aa0845  wkhtmltopdf_linux_amd64

Does anyone on Mac have a minute to check the darwin fingerprint or can someone tell me how to extract the official wkhtmltox-0.12.4_osx-cocoa-x86-64.pkg on Debian? Thanks!

**Comment by kimyu92** [comment]
@unixmonkey any reason to hold off on merging this PR and publish a new release to rubygems?
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5 is out too

**Comment by unixmonkey** [comment]
@ownadi Thank you very much for this. I'm sorry it took so long to get merged. I don't quite have the time for this that I used to, but I will try to get any 0.12.5 PR merged more quickly. If anyone would like to help with that once pre-built binaries are available, it would be much appreciated.

This new version has been pushed to RubyGems. Please be aware there is a [well known issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3241) with this version, but it can be worked around.

@baloran, @gkop, @kimyu92, @jeremiahmegel, @matthew342, @Subtletree Thanks for the support and nudging.

**Comment by sandergroen** [comment]
@unixmonkey maybe you can make the project part of an organization (just like https://github.com/wkhtmltopdf maybe wkhtmltopdf_binary_gem/wkhtmltopdf_binary_gem) and add maintainers to that so you are not the only maintainer. If you do not have time for it, someone else might.

I have no clue where to get those pre-build binaries otherwise I could add them.

**Comment by zakird** [comment]
I'm happy to add maintainers if there are folks who are actively contributing. I think it's a bit tough to add additional folks without seeing any history in the project.

**Pull request merged**
