### PR TITLE
Add support for Debian 11 (bullseye)

### PR DESCRIPTION
**Pull request by daniellytle**
* Adding Debian 11 binary
* Adding tests/dockerfile for Debian 11

### CODE REVIEW

**Comment by daniellytle** [comment]
@unixmonkey Could I get a look at this?

**Review by stuyam — APPROVED** [review]
Looks good!

**Comment by unixmonkey** [comment]
@daniellytle It seems this is failing in CI trying to run an older version on linux systems:

```
  1) Failure:
WithDockerTest#test_debian_11 [/home/runner/work/wkhtmltopdf_binary_gem/wkhtmltopdf_binary_gem/test/test_with_docker.rb:63]:
--- expected
+++ actual
@@ -1 +1 @@
-"wkhtmltopdf 0.12.6.1 (with patched qt)"
+"wkhtmltopdf 0.12.6 (with patched qt)"
```

**Comment by daniellytle** [comment]
> @daniellytle It seems this is failing in CI trying to run an older version on linux systems:
> 
> ```
>   1) Failure:
> WithDockerTest#test_debian_11 [/home/runner/work/wkhtmltopdf_binary_gem/wkhtmltopdf_binary_gem/test/test_with_docker.rb:63]:
> --- expected
> +++ actual
> @@ -1 +1 @@
> -"wkhtmltopdf 0.12.6.1 (with patched qt)"
> +"wkhtmltopdf 0.12.6 (with patched qt)"
> ```

Yep, re-bundled with the 0.12.6.1 binary from https://github.com/wkhtmltopdf/packaging/releases

**Comment by daniellytle** [comment]
@unixmonkey Could I get another workflow run on this?

**Comment by lusinh** [comment]
@daniellytle Could you update test for only debian_11 (pass CI to release)?

**Comment by unixmonkey** [comment]
@daniellytle Sorry I've missed the last few messages, and not addressed this in a timely manner. Is that why you closed this PR? I see that we could still use this contribution.

**Pull request closed without merging**
